Module 3 all tasks
js-tasks-ru/jsbasic-20210621_nikalayeva pull request #4
Opened 2021-07-05 12:58 UTC by anastasiyanikalayeva

2021-07-05 12:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-05 20:03 UTC, SinimaWath requested changes

2021-07-05 20:03 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return newArray;
Давай перепишем на map

2021-07-05 20:03 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return filteredArr;
Давай на filter переделаем

2021-07-05 20:03 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return strCamelCase;
Давай напишем в filter->map->join()

2021-07-05 20:03 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return strAllSalaries.slice(0, -1);
Давай переделаем на filter -> map

2021-07-06 18:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-07 16:43 UTC, SinimaWath requested changes
Давай еще поправим небольшие замечания

2021-07-07 16:43 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return newArray;
map -> как раз таки и делает push, елемента которое ты возвращаешь из функции.

Поэтому правильней будет вот так: `return users.map(item => item.name)`

2021-07-07 16:43 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  });
Давай все таки переделаем на стрелочную функцию, так как она понятней и там меньше букв.

2021-07-07 16:43 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return strCamelCase;
Давай в этом примере научимся использовать чейнинг:
```

arr.filter(...).map(...).join(...)
```

2021-07-07 16:43 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return newArr.join("").slice(0, -1);
Давай тут тоже попробуем чейнинг

2021-07-07 18:15 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-08 09:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-10 15:27 UTC, SinimaWath requested changes

2021-07-10 15:27 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return users.filter(user => user.age <= age).map(user => user.name + ", " + user.balance + "\n").join("").slice(0, -1);
тут нет необходимости в slice и в + "\n".

`join('\n')` - сделает все за тебя

2021-07-10 15:27 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return [arr[0]] + arr.filter((item, index) => index > 0).map(item => item[0].toUpperCase() + item.slice(1)).join('');
А зачем тут [arr[0]] ? Точнее какая идея была.

2021-07-10 15:27 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  document.body.append(list);
Не нужно добавлять список в body.

По задаче надо вернуть елемент из функции

2021-07-10 15:27 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    item.innerHTML = `${friend.firstName}` + ' ' + `${friend.lastName}`;
`${friend.firstName} ${friend.lastName}`

2021-07-10 15:27 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    item.innerHTML = `${friend.firstName}` + ' ' + `${friend.lastName}`;
В шаблонных строках можно не писать + ' ' +, они для этого и придуманны

2021-07-11 09:11 UTC, anastasiyanikalayeva commented on 3-module/3-task/index.js
> +  return [arr[0]] + arr.filter((item, index) => index > 0).map(item => item[0].toUpperCase() + item.slice(1)).join('');
Нам нужно добавить первый элемент массива, т.к. все преобразования мы делаем, начиная со второго элемента.

2021-07-11 09:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-11 10:36 UTC, SinimaWath requested changes

2021-07-11 10:36 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return [arr[0]] + arr.filter((item, index) => index > 0).map(item => item[0].toUpperCase() + item.slice(1)).join('');
[arr[0]] -> это будет массив из первого елемента: `['w']`

Если надо добавить первый елемент, то: `return arr[0] + ..`

2021-07-11 10:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-13 11:55 UTC, SinimaWath approved these changes

2021-07-13 11:56 UTC, merged